name: test # Name of our workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest # Environment job will run in

    steps: # Each action/command to run
    - uses: actions/checkout@v2 # Helps check out the repo code
    - uses: ./.github/actions/test
