
# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: get the site
        run: wget -nH -mkEpnp https://www.newsbtc.com/
      - uses: ./.github/actions/test
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
